<?php
/**
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (c) vtiger.
 * Portions created by IT-Solutions4You (ITS4You) are Copyright (c) IT-Solutions4You s.r.o
 * All Rights Reserved.
 */

require_once 'VTEntityData.inc';
require_once 'VTEntityType.inc';
require_once 'VTEventHandler.inc';
require_once 'VTEventsManager.inc';
require_once 'VTEventTrigger.inc';
require_once 'VTBatchData.inc';
require_once 'VTBatchEventTrigger.inc';