<?php
/*
 * This file is part of the IT-Solutions4You CRM Software.
 *
 * (c) IT-Solutions4You s.r.o [info@its4you.sk]
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

class SalesOrder_Install_Model extends Core_Install_Model {

    /**
     * @return void
     */
    public function addCustomLinks(): void
    {
    }

    /**
     * @return void
     */
    public function deleteCustomLinks(): void
    {
    }

    /**
     * @return array
     */
    public function getBlocks(): array
    {
        return [
            'LBL_SO_INFORMATION' => [
                'subject' => [
                    'name' => 'subject',
                    'uitype' => 2,
                    'column' => 'subject',
                    'table' => 'vtiger_salesorder',
                    'label' => 'Subject',
                    'readonly' => 1,
                    'presence' => 0,
                    'typeofdata' => 'V~M',
                    'quickcreate' => 3,
                    'displaytype' => 1,
                    'masseditable' => 1,
                    'summaryfield' => 1,
                    'entity_identifier' => 1,
                ],
                'potential_id' => [
                    'name' => 'potential_id',
                    'uitype' => 76,
                    'column' => 'potentialid',
                    'table' => 'vtiger_salesorder',
                    'label' => 'Potential Name',
                    'readonly' => 1,
                    'presence' => 2,
                    'typeofdata' => 'I~O',
                    'quickcreate' => 3,
                    'displaytype' => 1,
                    'masseditable' => 1,
                    'summaryfield' => 0,
                ],
                'customerno' => [
                    'name' => 'customerno',
                    'uitype' => 1,
                    'column' => 'customerno',
                    'table' => 'vtiger_salesorder',
                    'label' => 'Customer No',
                    'readonly' => 1,
                    'presence' => 2,
                    'typeofdata' => 'V~O',
                    'quickcreate' => 3,
                    'displaytype' => 1,
                    'masseditable' => 1,
                    'summaryfield' => 0,
                ],
                'quote_id' => [
                    'name' => 'quote_id',
                    'uitype' => 78,
                    'column' => 'quoteid',
                    'table' => 'vtiger_salesorder',
                    'label' => 'Quote Name',
                    'readonly' => 1,
                    'presence' => 2,
                    'typeofdata' => 'I~O',
                    'quickcreate' => 3,
                    'displaytype' => 1,
                    'masseditable' => 0,
                    'summaryfield' => 1,
                ],
                'vtiger_purchaseorder' => [
                    'name' => 'vtiger_purchaseorder',
                    'uitype' => 1,
                    'column' => 'purchaseorder',
                    'table' => 'vtiger_salesorder',
                    'label' => 'Purchase Order',
                    'readonly' => 1,
                    'presence' => 2,
                    'typeofdata' => 'V~O',
                    'quickcreate' => 3,
                    'displaytype' => 1,
                    'masseditable' => 1,
                    'summaryfield' => 0,
                ],
                'contact_id' => [
                    'name' => 'contact_id',
                    'uitype' => 57,
                    'column' => 'contactid',
                    'table' => 'vtiger_salesorder',
                    'label' => 'Contact Name',
                    'readonly' => 1,
                    'presence' => 2,
                    'typeofdata' => 'I~O',
                    'quickcreate' => 3,
                    'displaytype' => 1,
                    'masseditable' => 1,
                    'summaryfield' => 0,
                ],
                'duedate' => [
                    'name' => 'duedate',
                    'uitype' => 5,
                    'column' => 'duedate',
                    'table' => 'vtiger_salesorder',
                    'label' => 'Due Date',
                    'readonly' => 1,
                    'presence' => 2,
                    'typeofdata' => 'D~O',
                    'quickcreate' => 3,
                    'displaytype' => 1,
                    'masseditable' => 1,
                    'summaryfield' => 0,
                ],
                'carrier' => [
                    'name' => 'carrier',
                    'uitype' => 15,
                    'column' => 'carrier',
                    'table' => 'vtiger_salesorder',
                    'label' => 'Carrier',
                    'readonly' => 1,
                    'presence' => 2,
                    'typeofdata' => 'V~O',
                    'quickcreate' => 3,
                    'displaytype' => 1,
                    'masseditable' => 1,
                    'summaryfield' => 0,
                    'picklist_values' => [
                        'FedEx',
                        'UPS',
                        'USPS',
                        'DHL',
                        'BlueDart',
                    ],
                ],
                'pending' => [
                    'name' => 'pending',
                    'uitype' => 1,
                    'column' => 'pending',
                    'table' => 'vtiger_salesorder',
                    'label' => 'Pending',
                    'readonly' => 1,
                    'presence' => 2,
                    'typeofdata' => 'V~O',
                    'quickcreate' => 3,
                    'displaytype' => 1,
                    'masseditable' => 1,
                    'summaryfield' => 0,
                ],
                'sostatus' => [
                    'name' => 'sostatus',
                    'uitype' => 15,
                    'column' => 'sostatus',
                    'table' => 'vtiger_salesorder',
                    'label' => 'Status',
                    'readonly' => 1,
                    'presence' => 2,
                    'typeofdata' => 'V~M',
                    'quickcreate' => 3,
                    'displaytype' => 1,
                    'masseditable' => 1,
                    'summaryfield' => 0,
                    'picklist_values' => [
                        'Created',
                        'Approved',
                        'Delivered',
                        'Cancelled',
                    ],
                ],
                'txtAdjustment' => [
                    'name' => 'txtAdjustment',
                    'uitype' => 72,
                    'column' => 'adjustment',
                    'table' => 'vtiger_salesorder',
                    'label' => 'Adjustment',
                    'readonly' => 1,
                    'presence' => 2,
                    'typeofdata' => 'NN~O',
                    'quickcreate' => 3,
                    'displaytype' => 3,
                    'masseditable' => 1,
                    'summaryfield' => 0,
                ],
                'salescommission' => [
                    'name' => 'salescommission',
                    'uitype' => 1,
                    'column' => 'salescommission',
                    'table' => 'vtiger_salesorder',
                    'label' => 'Sales Commission',
                    'readonly' => 1,
                    'presence' => 2,
                    'typeofdata' => 'N~O',
                    'quickcreate' => 3,
                    'displaytype' => 1,
                    'masseditable' => 1,
                    'summaryfield' => 0,
                ],
                'exciseduty' => [
                    'name' => 'exciseduty',
                    'uitype' => 1,
                    'column' => 'exciseduty',
                    'table' => 'vtiger_salesorder',
                    'label' => 'Excise Duty',
                    'readonly' => 1,
                    'presence' => 2,
                    'typeofdata' => 'N~O',
                    'quickcreate' => 3,
                    'displaytype' => 1,
                    'masseditable' => 1,
                    'summaryfield' => 0,
                ],
                'hdnGrandTotal' => [
                    'name' => 'hdnGrandTotal',
                    'uitype' => 72,
                    'column' => 'total',
                    'table' => 'vtiger_salesorder',
                    'label' => 'Total',
                    'readonly' => 1,
                    'presence' => 2,
                    'typeofdata' => 'N~O',
                    'quickcreate' => 3,
                    'displaytype' => 3,
                    'masseditable' => 1,
                    'summaryfield' => 1,
                ],
                'hdnSubTotal' => [
                    'name' => 'hdnSubTotal',
                    'uitype' => 72,
                    'column' => 'subtotal',
                    'table' => 'vtiger_salesorder',
                    'label' => 'Sub Total',
                    'readonly' => 1,
                    'presence' => 2,
                    'typeofdata' => 'N~O',
                    'quickcreate' => 3,
                    'displaytype' => 3,
                    'masseditable' => 1,
                    'summaryfield' => 0,
                ],
                'hdnTaxType' => [
                    'name' => 'hdnTaxType',
                    'uitype' => 16,
                    'column' => 'taxtype',
                    'table' => 'vtiger_salesorder',
                    'label' => 'Tax Type',
                    'readonly' => 1,
                    'presence' => 2,
                    'typeofdata' => 'V~O',
                    'quickcreate' => 3,
                    'displaytype' => 3,
                    'masseditable' => 1,
                    'summaryfield' => 0,
                    'picklist_values' => [],
                ],
                'hdnS_H_Amount' => [
                    'name' => 'hdnS_H_Amount',
                    'uitype' => 72,
                    'column' => 's_h_amount',
                    'table' => 'vtiger_salesorder',
                    'label' => 'S&H Amount',
                    'readonly' => 1,
                    'presence' => 2,
                    'typeofdata' => 'N~O',
                    'quickcreate' => 3,
                    'displaytype' => 3,
                    'masseditable' => 1,
                    'summaryfield' => 0,
                ],
                'account_id' => [
                    'name' => 'account_id',
                    'uitype' => 73,
                    'column' => 'accountid',
                    'table' => 'vtiger_salesorder',
                    'label' => 'Account Name',
                    'readonly' => 1,
                    'presence' => 2,
                    'typeofdata' => 'I~M',
                    'quickcreate' => 3,
                    'displaytype' => 1,
                    'masseditable' => 1,
                    'summaryfield' => 0,
                ],
                'assigned_user_id' => [
                    'name' => 'assigned_user_id',
                    'uitype' => 53,
                    'column' => 'smownerid',
                    'table' => 'vtiger_crmentity',
                    'label' => 'Assigned To',
                    'readonly' => 1,
                    'presence' => 0,
                    'typeofdata' => 'V~M',
                    'quickcreate' => 3,
                    'displaytype' => 1,
                    'masseditable' => 1,
                    'summaryfield' => 0,
                ],
                'currency_id' => [
                    'name' => 'currency_id',
                    'uitype' => 117,
                    'column' => 'currency_id',
                    'table' => 'vtiger_salesorder',
                    'label' => 'Currency',
                    'readonly' => 1,
                    'presence' => 2,
                    'typeofdata' => 'I~O',
                    'quickcreate' => 3,
                    'displaytype' => 3,
                    'masseditable' => 1,
                    'summaryfield' => 0,
                ],
                'conversion_rate' => [
                    'name' => 'conversion_rate',
                    'uitype' => 1,
                    'column' => 'conversion_rate',
                    'table' => 'vtiger_salesorder',
                    'label' => 'Conversion Rate',
                    'readonly' => 1,
                    'presence' => 2,
                    'typeofdata' => 'N~O',
                    'quickcreate' => 3,
                    'displaytype' => 3,
                    'masseditable' => 1,
                    'summaryfield' => 0,
                ],
                'pre_tax_total' => [
                    'name' => 'pre_tax_total',
                    'uitype' => 72,
                    'column' => 'pre_tax_total',
                    'table' => 'vtiger_salesorder',
                    'label' => 'Pre Tax Total',
                    'readonly' => 1,
                    'presence' => 2,
                    'typeofdata' => 'N~O',
                    'quickcreate' => 1,
                    'displaytype' => 3,
                    'masseditable' => 1,
                    'summaryfield' => 0,
                ],
            ],
            'LBL_CUSTOM_INFORMATION' => [
            ],
            'LBL_ADDRESS_INFORMATION' => [
                'bill_street' => [
                    'name' => 'bill_street',
                    'uitype' => 24,
                    'column' => 'bill_street',
                    'table' => 'vtiger_sobillads',
                    'label' => 'Billing Street',
                    'readonly' => 1,
                    'presence' => 2,
                    'typeofdata' => 'V~M',
                    'quickcreate' => 3,
                    'displaytype' => 1,
                    'masseditable' => 1,
                    'summaryfield' => 0,
                ],
                'ship_street' => [
                    'name' => 'ship_street',
                    'uitype' => 24,
                    'column' => 'ship_street',
                    'table' => 'vtiger_soshipads',
                    'label' => 'Shipping Street',
                    'readonly' => 1,
                    'presence' => 2,
                    'typeofdata' => 'V~O',
                    'quickcreate' => 3,
                    'displaytype' => 1,
                    'masseditable' => 1,
                    'summaryfield' => 0,
                ],
                'bill_city' => [
                    'name' => 'bill_city',
                    'uitype' => 1,
                    'column' => 'bill_city',
                    'table' => 'vtiger_sobillads',
                    'label' => 'Billing City',
                    'readonly' => 1,
                    'presence' => 2,
                    'typeofdata' => 'V~O',
                    'quickcreate' => 3,
                    'displaytype' => 1,
                    'masseditable' => 1,
                    'summaryfield' => 0,
                ],
                'ship_city' => [
                    'name' => 'ship_city',
                    'uitype' => 1,
                    'column' => 'ship_city',
                    'table' => 'vtiger_soshipads',
                    'label' => 'Shipping City',
                    'readonly' => 1,
                    'presence' => 2,
                    'typeofdata' => 'V~O',
                    'quickcreate' => 3,
                    'displaytype' => 1,
                    'masseditable' => 1,
                    'summaryfield' => 0,
                ],
                'bill_state' => [
                    'name' => 'bill_state',
                    'uitype' => 1,
                    'column' => 'bill_state',
                    'table' => 'vtiger_sobillads',
                    'label' => 'Billing State',
                    'readonly' => 1,
                    'presence' => 2,
                    'typeofdata' => 'V~O',
                    'quickcreate' => 3,
                    'displaytype' => 1,
                    'masseditable' => 1,
                    'summaryfield' => 0,
                ],
                'ship_state' => [
                    'name' => 'ship_state',
                    'uitype' => 1,
                    'column' => 'ship_state',
                    'table' => 'vtiger_soshipads',
                    'label' => 'Shipping State',
                    'readonly' => 1,
                    'presence' => 2,
                    'typeofdata' => 'V~O',
                    'quickcreate' => 3,
                    'displaytype' => 1,
                    'masseditable' => 1,
                    'summaryfield' => 0,
                ],
                'bill_code' => [
                    'name' => 'bill_code',
                    'uitype' => 1,
                    'column' => 'bill_code',
                    'table' => 'vtiger_sobillads',
                    'label' => 'Billing Code',
                    'readonly' => 1,
                    'presence' => 2,
                    'typeofdata' => 'V~O',
                    'quickcreate' => 3,
                    'displaytype' => 1,
                    'masseditable' => 1,
                    'summaryfield' => 0,
                ],
                'ship_code' => [
                    'name' => 'ship_code',
                    'uitype' => 1,
                    'column' => 'ship_code',
                    'table' => 'vtiger_soshipads',
                    'label' => 'Shipping Code',
                    'readonly' => 1,
                    'presence' => 2,
                    'typeofdata' => 'V~O',
                    'quickcreate' => 3,
                    'displaytype' => 1,
                    'masseditable' => 1,
                    'summaryfield' => 0,
                ],
                'bill_country_id' => [
                    'name' => 'bill_country_id',
                    'uitype' => 18,
                    'column' => 'bill_country_id',
                    'table' => 'vtiger_sobillads',
                    'label' => 'Billing Country',
                    'readonly' => 1,
                    'presence' => 2,
                    'typeofdata' => 'V~O',
                    'quickcreate' => 3,
                    'displaytype' => 1,
                    'masseditable' => 1,
                    'summaryfield' => 0,
                ],
                'ship_country_id' => [
                    'name' => 'ship_country_id',
                    'uitype' => 18,
                    'column' => 'ship_country_id',
                    'table' => 'vtiger_soshipads',
                    'label' => 'Shipping Country',
                    'readonly' => 1,
                    'presence' => 2,
                    'typeofdata' => 'V~O',
                    'quickcreate' => 3,
                    'displaytype' => 1,
                    'masseditable' => 1,
                    'summaryfield' => 0,
                ],
                'bill_pobox' => [
                    'name' => 'bill_pobox',
                    'uitype' => 1,
                    'column' => 'bill_pobox',
                    'table' => 'vtiger_sobillads',
                    'label' => 'Billing Po Box',
                    'readonly' => 1,
                    'presence' => 2,
                    'typeofdata' => 'V~O',
                    'quickcreate' => 3,
                    'displaytype' => 1,
                    'masseditable' => 1,
                    'summaryfield' => 0,
                ],
                'ship_pobox' => [
                    'name' => 'ship_pobox',
                    'uitype' => 1,
                    'column' => 'ship_pobox',
                    'table' => 'vtiger_soshipads',
                    'label' => 'Shipping Po Box',
                    'readonly' => 1,
                    'presence' => 2,
                    'typeofdata' => 'V~O',
                    'quickcreate' => 3,
                    'displaytype' => 1,
                    'masseditable' => 1,
                    'summaryfield' => 0,
                ],
            ],
            'LBL_TERMS_INFORMATION' => [
                'terms_conditions' => [
                    'name' => 'terms_conditions',
                    'uitype' => 19,
                    'column' => 'terms_conditions',
                    'table' => 'vtiger_salesorder',
                    'label' => 'Terms & Conditions',
                    'readonly' => 1,
                    'presence' => 2,
                    'typeofdata' => 'V~O',
                    'quickcreate' => 3,
                    'displaytype' => 1,
                    'masseditable' => 1,
                    'summaryfield' => 0,
                ],
            ],
            'LBL_DESCRIPTION_INFORMATION' => [
                'description' => [
                    'name' => 'description',
                    'uitype' => 19,
                    'column' => 'description',
                    'table' => 'vtiger_crmentity',
                    'label' => 'Description',
                    'readonly' => 1,
                    'presence' => 2,
                    'typeofdata' => 'V~O',
                    'quickcreate' => 3,
                    'displaytype' => 1,
                    'masseditable' => 1,
                    'summaryfield' => 0,
                ],
            ],
            'Recurring Invoice Information' => [
                'enable_recurring' => [
                    'name' => 'enable_recurring',
                    'uitype' => 56,
                    'column' => 'enable_recurring',
                    'table' => 'vtiger_salesorder',
                    'label' => 'Enable Recurring',
                    'readonly' => 1,
                    'presence' => 0,
                    'typeofdata' => 'C~O',
                    'quickcreate' => 3,
                    'displaytype' => 1,
                    'masseditable' => 0,
                    'summaryfield' => 0,
                ],
                'recurring_frequency' => [
                    'name' => 'recurring_frequency',
                    'uitype' => 16,
                    'column' => 'recurring_frequency',
                    'table' => 'vtiger_invoice_recurring_info',
                    'label' => 'Frequency',
                    'readonly' => 1,
                    'presence' => 0,
                    'typeofdata' => 'V~O',
                    'quickcreate' => 3,
                    'displaytype' => 1,
                    'masseditable' => 0,
                    'summaryfield' => 0,
                    'picklist_values' => [
                        'Daily',
                        'Weekly',
                        'Monthly',
                        'Quarterly',
                        'Yearly',
                    ],
                ],
                'start_period' => [
                    'name' => 'start_period',
                    'uitype' => 5,
                    'column' => 'start_period',
                    'table' => 'vtiger_invoice_recurring_info',
                    'label' => 'Start Period',
                    'readonly' => 1,
                    'presence' => 0,
                    'typeofdata' => 'D~O',
                    'quickcreate' => 3,
                    'displaytype' => 1,
                    'masseditable' => 0,
                    'summaryfield' => 0,
                ],
                'end_period' => [
                    'name' => 'end_period',
                    'uitype' => 5,
                    'column' => 'end_period',
                    'table' => 'vtiger_invoice_recurring_info',
                    'label' => 'End Period',
                    'readonly' => 1,
                    'presence' => 0,
                    'typeofdata' => 'D~O~OTH~G~start_period~Start Period',
                    'quickcreate' => 3,
                    'displaytype' => 1,
                    'masseditable' => 0,
                    'summaryfield' => 0,
                ],
                'payment_duration' => [
                    'name' => 'payment_duration',
                    'uitype' => 16,
                    'column' => 'payment_duration',
                    'table' => 'vtiger_invoice_recurring_info',
                    'label' => 'Payment Duration',
                    'readonly' => 1,
                    'presence' => 0,
                    'typeofdata' => 'V~O',
                    'quickcreate' => 3,
                    'displaytype' => 1,
                    'masseditable' => 0,
                    'summaryfield' => 0,
                    'picklist_values' => [
                        'Net 30 days',
                        'Net 45 days',
                        'Net 60 days',
                    ],
                ],
                'invoicestatus' => [
                    'name' => 'invoicestatus',
                    'uitype' => 15,
                    'column' => 'invoice_status',
                    'table' => 'vtiger_invoice_recurring_info',
                    'label' => 'Invoice Status',
                    'readonly' => 1,
                    'presence' => 0,
                    'typeofdata' => 'V~M',
                    'quickcreate' => 3,
                    'displaytype' => 1,
                    'masseditable' => 0,
                    'summaryfield' => 0,
                    'picklist_values' => [
                        'AutoCreated',
                        'Created',
                        'Approved',
                        'Sent',
                        'Credit Invoice',
                        'Paid',
                        'Cancel',
                    ],
                ],
                'last_recurring_date' => [
                    'name' => 'last_recurring_date',
                    'uitype' => 5,
                    'column' => 'last_recurring_date',
                    'table' => 'vtiger_invoice_recurring_info',
                    'label' => 'Next Invoice Date',
                    'typeofdata' => 'D~O',
                    'displaytype' => 2,
                    'columntype' => 'date',
                ],
            ],
            'LBL_ITEM_DETAILS' => [
                'hdnDiscountPercent' => [
                    'name' => 'hdnDiscountPercent',
                    'uitype' => 1,
                    'column' => 'discount_percent',
                    'table' => 'vtiger_salesorder',
                    'label' => 'Discount Percent',
                    'readonly' => 1,
                    'presence' => 2,
                    'typeofdata' => 'N~O',
                    'quickcreate' => 3,
                    'displaytype' => 5,
                    'masseditable' => 1,
                    'summaryfield' => 0,
                ],
                'hdnDiscountAmount' => [
                    'name' => 'hdnDiscountAmount',
                    'uitype' => 72,
                    'column' => 'discount_amount',
                    'table' => 'vtiger_salesorder',
                    'label' => 'Discount Amount',
                    'readonly' => 1,
                    'presence' => 0,
                    'typeofdata' => 'N~O',
                    'quickcreate' => 3,
                    'displaytype' => 5,
                    'masseditable' => 1,
                    'summaryfield' => 0,
                ],
                'productid' => [
                    'name' => 'productid',
                    'uitype' => 10,
                    'column' => 'productid',
                    'table' => 'vtiger_inventoryproductrel',
                    'label' => 'Item Name',
                    'readonly' => 0,
                    'presence' => 2,
                    'typeofdata' => 'V~M',
                    'quickcreate' => 1,
                    'displaytype' => 5,
                    'masseditable' => 0,
                    'summaryfield' => 0,
                    'related_modules' => [
                        'Products',
                        'Services',
                    ],
                ],
                'quantity' => [
                    'name' => 'quantity',
                    'uitype' => 7,
                    'column' => 'quantity',
                    'table' => 'vtiger_inventoryproductrel',
                    'label' => 'Quantity',
                    'readonly' => 0,
                    'presence' => 2,
                    'typeofdata' => 'N~O',
                    'quickcreate' => 1,
                    'displaytype' => 5,
                    'masseditable' => 0,
                    'summaryfield' => 0,
                ],
                'listprice' => [
                    'name' => 'listprice',
                    'uitype' => 71,
                    'column' => 'listprice',
                    'table' => 'vtiger_inventoryproductrel',
                    'label' => 'List Price',
                    'readonly' => 0,
                    'presence' => 2,
                    'typeofdata' => 'N~O',
                    'quickcreate' => 1,
                    'displaytype' => 5,
                    'masseditable' => 0,
                    'summaryfield' => 0,
                ],
                'comment' => [
                    'name' => 'comment',
                    'uitype' => 19,
                    'column' => 'comment',
                    'table' => 'vtiger_inventoryproductrel',
                    'label' => 'Item Comment',
                    'readonly' => 0,
                    'presence' => 2,
                    'typeofdata' => 'V~O',
                    'quickcreate' => 1,
                    'displaytype' => 5,
                    'masseditable' => 0,
                    'summaryfield' => 0,
                ],
                'discount_amount' => [
                    'name' => 'discount_amount',
                    'uitype' => 71,
                    'column' => 'discount_amount',
                    'table' => 'vtiger_inventoryproductrel',
                    'label' => 'Item Discount Amount',
                    'readonly' => 0,
                    'presence' => 2,
                    'typeofdata' => 'N~O',
                    'quickcreate' => 1,
                    'displaytype' => 5,
                    'masseditable' => 0,
                    'summaryfield' => 0,
                ],
                'discount_percent' => [
                    'name' => 'discount_percent',
                    'uitype' => 7,
                    'column' => 'discount_percent',
                    'table' => 'vtiger_inventoryproductrel',
                    'label' => 'Item Discount Percent',
                    'readonly' => 0,
                    'presence' => 2,
                    'typeofdata' => 'V~O',
                    'quickcreate' => 1,
                    'displaytype' => 5,
                    'masseditable' => 0,
                    'summaryfield' => 0,
                ],
                'hdnS_H_Percent' => [
                    'name' => 'hdnS_H_Percent',
                    'uitype' => 1,
                    'column' => 's_h_percent',
                    'table' => 'vtiger_salesorder',
                    'label' => 'S&H Percent',
                    'readonly' => 0,
                    'presence' => 2,
                    'typeofdata' => 'N~O',
                    'quickcreate' => 0,
                    'displaytype' => 5,
                    'masseditable' => 0,
                    'summaryfield' => 0,
                ],
                'image' => [
                    'name' => 'image',
                    'uitype' => 56,
                    'column' => 'image',
                    'table' => 'vtiger_inventoryproductrel',
                    'label' => 'Image',
                    'readonly' => 0,
                    'presence' => 1,
                    'typeofdata' => 'V~O',
                    'quickcreate' => 1,
                    'displaytype' => 5,
                    'masseditable' => 0,
                    'summaryfield' => 0,
                ],
                'purchase_cost' => [
                    'name' => 'purchase_cost',
                    'uitype' => 71,
                    'column' => 'purchase_cost',
                    'table' => 'vtiger_inventoryproductrel',
                    'label' => 'Purchase Cost',
                    'readonly' => 0,
                    'presence' => 1,
                    'typeofdata' => 'N~O',
                    'quickcreate' => 1,
                    'displaytype' => 5,
                    'masseditable' => 0,
                    'summaryfield' => 0,
                ],
                'margin' => [
                    'name' => 'margin',
                    'uitype' => 71,
                    'column' => 'margin',
                    'table' => 'vtiger_inventoryproductrel',
                    'label' => 'Margin',
                    'readonly' => 0,
                    'presence' => 1,
                    'typeofdata' => 'N~O',
                    'quickcreate' => 1,
                    'displaytype' => 5,
                    'masseditable' => 0,
                    'summaryfield' => 0,
                ],
                'region_id' => [
                    'name' => 'region_id',
                    'uitype' => 16,
                    'column' => 'region_id',
                    'table' => 'vtiger_salesorder',
                    'label' => 'Tax Region',
                    'readonly' => 0,
                    'presence' => 2,
                    'typeofdata' => 'N~O',
                    'quickcreate' => 1,
                    'displaytype' => 5,
                    'masseditable' => 0,
                    'summaryfield' => 0,
                    'picklist_values' => [],
                ],
            ],
            'LBL_SYSTEM_INFORMATION' => [
                'salesorder_no' => [
                    'name' => 'salesorder_no',
                    'uitype' => 4,
                    'column' => 'salesorder_no',
                    'table' => 'vtiger_salesorder',
                    'label' => 'SalesOrder No',
                    'readonly' => 1,
                    'presence' => 0,
                    'typeofdata' => 'V~O',
                    'quickcreate' => 3,
                    'displaytype' => 1,
                    'masseditable' => 0,
                    'summaryfield' => 1,
                ],
            ]
        ];
    }

    /**
     * @return array
     */
    public function getTables(): array
    {
        return [];
    }

    /**
     * @return void
     * @throws AppException
     */
    public function installTables(): void
    {
        $this->getTable('vtiger_salesorder', null)
            ->createTable('salesorderid', 'int(19) NOT NULL DEFAULT \'0\'')
            ->createColumn('subject', 'varchar(100) DEFAULT NULL')
            ->createColumn('potentialid', 'int(19) DEFAULT NULL')
            ->createColumn('customerno', 'varchar(100) DEFAULT NULL')
            ->createColumn('salesorder_no', 'varchar(100) DEFAULT NULL')
            ->createColumn('quoteid', 'int(19) DEFAULT NULL')
            ->createColumn('vendorterms', 'varchar(100) DEFAULT NULL')
            ->createColumn('contactid', 'int(19) DEFAULT NULL')
            ->createColumn('vendorid', 'int(19) DEFAULT NULL')
            ->createColumn('duedate', 'date DEFAULT NULL')
            ->createColumn('carrier', 'varchar(200) DEFAULT NULL')
            ->createColumn('pending', 'varchar(200) DEFAULT NULL')
            ->createColumn('type', 'varchar(100) DEFAULT NULL')
            ->createColumn('adjustment', self::$COLUMN_DECIMAL)
            ->createColumn('salescommission', self::$COLUMN_DECIMAL)
            ->createColumn('exciseduty', self::$COLUMN_DECIMAL)
            ->createColumn('total', self::$COLUMN_DECIMAL)
            ->createColumn('subtotal', self::$COLUMN_DECIMAL)
            ->createColumn('taxtype', 'varchar(25) DEFAULT NULL')
            ->createColumn('discount_percent', self::$COLUMN_DECIMAL)
            ->createColumn('discount_amount', self::$COLUMN_DECIMAL)
            ->createColumn('s_h_amount', self::$COLUMN_DECIMAL)
            ->createColumn('accountid', 'int(19) DEFAULT NULL')
            ->createColumn('terms_conditions', 'text DEFAULT NULL')
            ->createColumn('purchaseorder', 'varchar(200) DEFAULT NULL')
            ->createColumn('sostatus', 'varchar(200) DEFAULT NULL')
            ->createColumn('currency_id', 'int(19) NOT NULL DEFAULT \'1\'')
            ->createColumn('conversion_rate', 'decimal(10,3) NOT NULL DEFAULT \'1.000\'')
            ->createColumn('enable_recurring', 'int(11) DEFAULT \'0\'')
            ->createColumn('compound_taxes_info', 'text DEFAULT NULL')
            ->createColumn('pre_tax_total', self::$COLUMN_DECIMAL)
            ->createColumn('s_h_percent', self::$COLUMN_DECIMAL)
            ->createColumn('tags', 'varchar(1) DEFAULT NULL')
            ->createColumn('region_id', 'int(19) DEFAULT NULL')
            ->createKey('PRIMARY KEY IF NOT EXISTS (`salesorderid`)')
            ->createKey('KEY IF NOT EXISTS `salesorder_vendorid_idx` (`vendorid`)')
            ->createKey('KEY IF NOT EXISTS `salesorder_contactid_idx` (`contactid`)')
            ->createKey('CONSTRAINT `fk_3_vtiger_salesorder` FOREIGN KEY IF NOT EXISTS (`vendorid`) REFERENCES `vtiger_vendor` (`vendorid`) ON DELETE CASCADE')
            ->createKey('CONSTRAINT `fk_crmid_vtiger_salesorder` FOREIGN KEY IF NOT EXISTS (`salesorderid`) REFERENCES `vtiger_crmentity` (`crmid`) ON DELETE CASCADE')
            ;

        $this->getTable('vtiger_sobillads', null)
            ->createColumn('sobilladdressid', 'int(19) NOT NULL DEFAULT \'0\'')
            ->createColumn('bill_city', 'varchar(150) DEFAULT NULL')
            ->createColumn('bill_code', 'varchar(150) DEFAULT NULL')
            ->createColumn('bill_country_id', 'varchar(2) DEFAULT NULL')
            ->createColumn('bill_state', 'varchar(150) DEFAULT NULL')
            ->createColumn('bill_street', 'varchar(250) DEFAULT NULL')
            ->createColumn('bill_pobox', 'varchar(30) DEFAULT NULL')
            ->createKey('PRIMARY KEY IF NOT EXISTS (`sobilladdressid`)')
            ->createKey('CONSTRAINT `fk_1_vtiger_sobillads` FOREIGN KEY IF NOT EXISTS (`sobilladdressid`) REFERENCES `vtiger_salesorder` (`salesorderid`) ON DELETE CASCADE')
        ;

        $this->getTable('vtiger_soshipads', null)
            ->createColumn('soshipaddressid', 'int(19) NOT NULL DEFAULT \'0\'')
            ->createColumn('ship_city', 'varchar(150) DEFAULT NULL')
            ->createColumn('ship_code', 'varchar(150) DEFAULT NULL')
            ->createColumn('ship_country_id', 'varchar(2) DEFAULT NULL')
            ->createColumn('ship_state', 'varchar(150) DEFAULT NULL')
            ->createColumn('ship_street', 'varchar(250) DEFAULT NULL')
            ->createColumn('ship_pobox', 'varchar(30) DEFAULT NULL')
            ->createKey('PRIMARY KEY IF NOT EXISTS (`soshipaddressid`)')
            ->createKey('CONSTRAINT `fk_1_vtiger_soshipads` FOREIGN KEY IF NOT EXISTS (`soshipaddressid`) REFERENCES `vtiger_salesorder` (`salesorderid`) ON DELETE CASCADE')
        ;

        $this->createPicklistTable('vtiger_sostatus', 'sostatusid', 'sostatus');
        $this->createPicklistTable('vtiger_recurring_frequency', 'recurring_frequency_id', 'recurring_frequency');
        $this->createPicklistTable('vtiger_payment_duration', 'payment_duration_id', 'payment_duration');
    }
}