<?php

/**
 * This file is part of the IT-Solutions4You CRM Software.
 *
 * (c) IT-Solutions4You s.r.o [info@its4you.sk]
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
class Appointments_Datetime_UIType extends Vtiger_Datetime_UIType
{
    /**
     * @param $value
     * @return string
     */
    public function getEditValue($value): string
    {
        $dateValue = '';

        if ('' !== $value) {
            $dateTimeValue = self::getDisplayDateTimeValue($value);
            list($startDate, $startTime) = explode(' ', $dateTimeValue);

            $currentUser = Users_Record_Model::getCurrentUserModel();

            if ($currentUser->get('hour_format') == '12') {
                $startTime = Vtiger_Time_UIType::getTimeValueInAMorPM($startTime);
            }

            $dateValue = "$startDate $startTime";
        }

        return $dateValue;
    }

    /**
     * @param string $value
     * @return string
     */
    public function getEditViewDisplayValue($value): string
    {
        $fieldName = $this->get('field')->getName();

        if (empty($value)) {
            switch ($fieldName) {
                case 'datetime_start':
                    $value = date('Y-m-d H:i:s');
                    break;
                case 'datetime_end':
                    $currentUser = Users_Record_Model::getCurrentUserModel();
                    $minutes = $currentUser->get('callduration');
                    $value = date('Y-m-d H:i:s', strtotime("+$minutes minutes"));
                    break;
            }
        } else {
            switch ($fieldName) {
                case 'datetime_end':
                case 'datetime_start':
                    return $this->getEditValue($value);
            }
        }

        return parent::getEditViewDisplayValue($value); // TODO: Change the autogenerated stub
    }
}