<?php
/**
 * This file is part of Defalto – a CRM software developed by IT-Solutions4You s.r.o.
 *
 * (c) IT-Solutions4You s.r.o
 *
 * This file is licensed under the GNU AGPL v3 License.
 * See LICENSE-AGPLv3.txt for more details.
 */

class Appointments_Datetime_UIType extends Vtiger_Datetime_UIType
{
    /**
     * @param $value
     *
     * @return string
     */
    public function getEditValue($value): string
    {
        $dateValue = '';

        if ('' !== $value) {
            $dateTimeValue = self::getDisplayDateTimeValue($value);
            [$startDate, $startTime] = explode(' ', $dateTimeValue);

            $currentUser = Users_Record_Model::getCurrentUserModel();

            if ($currentUser->get('hour_format') == '12') {
                $startTime = Vtiger_Time_UIType::getTimeValueInAMorPM($startTime);
            }

            $dateValue = "$startDate $startTime";
        }

        return $dateValue;
    }

    /**
     * @param string $value
     *
     * @return string
     */
    public function getEditViewDisplayValue($value): string
    {
        $fieldName = $this->get('field')->getName();

        if (empty($value)) {
            switch ($fieldName) {
                case 'datetime_start':
                    $value = date('Y-m-d H:i:s');
                    break;
                case 'datetime_end':
                    $currentUser = Users_Record_Model::getCurrentUserModel();
                    $minutes = $currentUser->get('callduration');
                    $value = date('Y-m-d H:i:s', strtotime("+$minutes minutes"));
                    break;
            }
        } else {
            switch ($fieldName) {
                case 'datetime_end':
                case 'datetime_start':
                    return $this->getEditValue($value);
            }
        }

        return parent::getEditViewDisplayValue($value); // TODO: Change the autogenerated stub
    }
}