<?php
/**
 * This file is part of Defalto – a CRM software developed by IT-Solutions4You s.r.o.
 *
 * (c) IT-Solutions4You s.r.o
 *
 * This file is licensed under the GNU AGPL v3 License.
 * See LICENSE-AGPLv3.txt for more details.
 */

class Appointments_InviteUsers_UIType extends Vtiger_Base_UIType
{
    /**
     * @return array
     */
    public function getAccessibleUsers(): array
    {
        return Appointments_InvitedUsers_Model::getAccessibleUsers();
    }

    public function getDBInsertValue($value): string
    {
        return !empty($value) && is_array($value) ? implode(',', $value) : $value; // TODO: Change the autogenerated stub
    }

    /**
     * @param mixed      $value
     * @param int|bool   $record
     * @param int|object $recordInstance
     *
     * @return string
     */
    public function getDisplayValue($value, $record = false, $recordInstance = false)
    {
        if (empty($record)) {
            return '';
        }

        $invitedUsers = Appointments_InvitedUsers_Model::getInstance($record);
        $invitedUsers->retrieveUsers();

        return implode(', ', array_intersect_key($invitedUsers::getAccessibleUsers(), $invitedUsers->getUsersInfo()));
    }

    public function getInvitedUsers($record): array
    {
        if (empty($record)) {
            return [];
        }

        $invitedUsers = Appointments_InvitedUsers_Model::getInstance($record);
        $invitedUsers->retrieveUsers();

        return $invitedUsers->getUsers();
    }

    /**
     * @return string
     */
    public function getTemplateName(): string
    {
        return 'uitypes/InviteUsers.tpl';
    }
}