<?php

/**
 * This file is part of the IT-Solutions4You CRM Software.
 *
 * (c) IT-Solutions4You s.r.o [info@its4you.sk]
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
class Appointments_InviteUsers_UIType extends Vtiger_Base_UIType
{
    /**
     * @return array
     */
    public function getAccessibleUsers(): array
    {
        return Appointments_InvitedUsers_Model::getAccessibleUsers();
    }

    public function getDBInsertValue($value): string
    {
        return !empty($value) && is_array($value) ? implode(',', $value) : $value; // TODO: Change the autogenerated stub
    }

    /**
     * @param mixed $value
     * @param int|bool $record
     * @param int|object $recordInstance
     * @return string
     */
    public function getDisplayValue($value, $record = false, $recordInstance = false)
    {
        if (empty($record)) {
            return '';
        }

        $invitedUsers = Appointments_InvitedUsers_Model::getInstance($record);
        $invitedUsers->retrieveUsers();

        return implode(', ', array_intersect_key($invitedUsers::getAccessibleUsers(), $invitedUsers->getUsersInfo()));
    }

    public function getInvitedUsers($record): array
    {
        if (empty($record)) {
            return [];
        }

        $invitedUsers = Appointments_InvitedUsers_Model::getInstance($record);
        $invitedUsers->retrieveUsers();

        return $invitedUsers->getUsers();
    }

    /**
     * @return string
     */
    public function getTemplateName(): string
    {
        return 'uitypes/InviteUsers.tpl';
    }
}