<?php
/*
 * This file is part of Defalto – a CRM software developed by IT-Solutions4You s.r.o.
 *
 * (c) IT-Solutions4You s.r.o
 *
 * This file is licensed under the GNU AGPL v3 License.
 * See LICENSE-AGPLv3.txt for more details.
 */

class Core_Color_UIType extends Vtiger_Base_UIType
{
    public static array $colors = [
        'Reds' => [
            'snow' => '#FFFAFA',
            'mistyrose' => '#FBE0E6',
            'lavenderblush' => '#FAD7E2',
            'pink' => '#F6CED9',
            'lightpink' => '#F4BECB',
            'lightcoral' => '#F49EB5',
            'rosybrown' => '#E0A3B2',
            'palevioletred' => '#E889A3',
            'lightsalmon' => '#F68979',
            'hotpink' => '#F2799A',
            'coral' => '#F7796A',
            'orangered' => '#FF6B6B',
            'darksalmon' => '#F76B76',
            'salmon' => '#F66A7C',
            'indianred' => '#E36A7C',
            'deeppink' => '#F06587',
            'red' => '#F5587D',
            'crimson' => '#E44D72',
            'mediumvioletred' => '#D94B7A',
            'firebrick' => '#D94A6A',
            'maroon' => '#BE4F6D',
            'tomato' => '#FF365F',
            'darkred' => '#AB475E',
            'brown' => '#8F4250',
        ],
        'Oranges' => [
            'floralwhite' => '#FFFAF0',
            'lightyellow' => '#FEFAEF',
            'seashell' => '#FFF5EB',
            'linen' => '#FAF3E8',
            'oldlace' => '#F9F3E4',
            'blanchedalmond' => '#F9ECD4',
            'papayawhip' => '#FDEBC8',
            'antiquewhite' => '#F6EAD5',
            'bisque' => '#F4E6C9',
            'moccasin' => '#ECDFC2',
            'navajowhite' => '#F7DEB0',
            'wheat' => '#F5DEB3',
            'peachpuff' => '#F8D9B0',
            'burlywood' => '#E6C7A1',
            'gold' => '#F1C44E',
            'sandybrown' => '#F4B183',
            'goldenrod' => '#E6B93D',
            'tan' => '#D2B48C',
            'orange' => '#F2A85E',
            'darkorange' => '#E59445',
        ],
        'Yellows' => [
            'ivory' => '#FDFBE9',
            'beige' => '#F7F1DC',
            'cornsilk' => '#FFF1C4',
            'lemonchiffon' => '#FBF1C9',
            'lightgoldenrodyellow' => '#F3E9C2',
            'palegoldenrod' => '#F7E9B3',
            'khaki' => '#F0D98B',
            'yellow' => '#F4CF5E',
            'darkkhaki' => '#D4C06F',
        ],
        'Greens' => [
            'honeydew' => '#E6F9EF',
            'mintcream' => '#CFFCDB',
            'palegreen' => '#C8F4D4',
            'lightgreen' => '#BDF5C9',
            'greenyellow' => '#A3F07D',
            'lawngreen' => '#7FF081',
            'chartreuse' => '#7AF27A',
            'mediumspringgreen' => '#65F2A4',
            'springgreen' => '#61EA9F',
            'lime' => '#6FF08A',
            'aquamarine' => '#79E6C4',
            'yellowgreen' => '#9EDB5C',
            'darkseagreen' => '#8FD6A7',
            'mediumaquamarine' => '#73D9B0',
            'green' => '#5CE573',
            'limegreen' => '#62DA79',
            'lightseagreen' => '#52C985',
            'mediumseagreen' => '#4FC281',
            'olive' => '#88B95A',
            'seagreen' => '#4FBF87',
            'forestgreen' => '#4FBF75',
            'olivedrab' => '#7DA64F',
            'darkgreen' => '#47AB5E',
            'darkolivegreen' => '#6E9F5A',
        ],
        'Blues' => [
            'azure' => '#F1F6FF',
            'lavender' => '#EFF3FE',
            'aliceblue' => '#EEF3FF',
            'lightcyan' => '#E2E9FE',
            'paleturquoise' => '#DBE2F6',
            'powderblue' => '#DBE6FF',
            'lightblue' => '#C8D6FB',
            'lightsteelblue' => '#B7C6E8',
            'lightskyblue' => '#9FC0FF',
            'skyblue' => '#8BB6FF',
            'cyan' => '#74BDF7',
            'aqua' => '#6FA8F8',
            'turquoise' => '#6BA2F0',
            'darkturquoise' => '#4DB6A6',
            'teal' => '#4AB0A1',
            'deepskyblue' => '#5FA6FF',
            'mediumpurple' => '#9C8FE6',
            'cornflowerblue' => '#6D8DF6',
            'cadetblue' => '#5F8FB3',
            'blue' => '#5E81F4',
            'indigo' => '#5B7DEC',
            'mediumslateblue' => '#667EEA',
            'royalblue' => '#5A78F0',
            'slateblue' => '#6477D8',
            'blueviolet' => '#7B6DE3',
            'darkcyan' => '#4A7FA6',
            'dodgerblue' => '#4F73F0',
            'mediumblue' => '#516FE4',
            'mediumturquoise' => '#4E6BDD',
            'steelblue' => '#4C6CC9',
            'darkblue' => '#475EAB',
            'darkslateblue' => '#445BA5',
            'midnightblue' => '#3F4F91',
            'navy' => '#3D4C8C',
        ],
        'Purples' => [
            'thistle' => '#F3E6F5',
            'plum' => '#E6C9F2',
            'violet' => '#C2A4F2',
            'orchid' => '#D18FE6',
            'mediumorchid' => '#B077E6',
            'fuchsia' => '#B26DDC',
            'magenta' => '#AC69D5',
            'purple' => '#8E6DD8',
            'darkorchid' => '#9B5FBF',
            'darkviolet' => '#7A4FE3',
            'darkmagenta' => '#8A4F9C',
        ],
        'Browns' => [
            'darkgoldenrod' => '#CFA632',
            'peru' => '#D99063',
            'chocolate' => '#9E5B3A',
            'sienna' => '#8F4A32',
            'saddlebrown' => '#7A3F2A',
        ],
        'Greys' => [
            'white' => '#FFFFFF',
            'whitesmoke' => '#F7F9FF',
            'ghostwhite' => '#F4F6FF',
            'gainsboro' => '#E5E7EB',
            'lightgray' => '#DEE0E3',
            'silver' => '#D1D5DB',
            'gray' => '#9CA3AF',
            'lightslategray' => '#94A3B8',
            'slategray' => '#64748B',
            'darkgray' => '#6B7280',
            'dimgray' => '#4B5563',
            'darkslategray' => '#374151',
            'black' => '#000000',
        ],
    ];

    public static function getColorList(): array
    {
        return self::$colors;
    }
}

