<?php
/**
 * This file is part of Defalto – a CRM software developed by IT-Solutions4You s.r.o.
 *
 * (c) IT-Solutions4You s.r.o
 *
 * This file is licensed under the GNU AGPL v3 License.
 * See LICENSE-AGPLv3.txt for more details.
 */

class PDFMaker_PDFMaker_Model extends Vtiger_Module_Model
{
    public $log;
    public $db;
    private $version_type = 'Free';
    private $version_no;
    private $basicModules;
    private $pageFormats;

    function __construct()
    {
        PDFMaker_Debugger_Model::GetInstance()->Init();

        global $log;

        $this->log = $log;
        $this->db = PearDatabase::getInstance();

        $this->basicModules = ['20', '21', '22', '23'];
        $this->name = 'PDFMaker';
        $this->id = getTabId($this->name);

        $_SESSION['KCFINDER']['uploadURL'] = rtrim(vglobal('site_URL'), '/') . '/test/upload';
        $_SESSION['KCFINDER']['uploadDir'] = __DIR__ . '/../../../test/upload';
    }

    //ListView data
    public function GetListviewData()
    {
        $params = ['Invoice', 'Quotes', 'SalesOrder', 'PurchaseOrder'];
        $sql = 'SELECT vtiger_pdfmaker.templateid, vtiger_pdfmaker.description, vtiger_pdfmaker.module FROM vtiger_pdfmaker LEFT JOIN vtiger_pdfmaker_settings USING(templateid) WHERE module IN (?, ?, ?, ?)';
        $result = $this->db->pquery($sql, $params);
        $templates = [];

        while ($row = $this->db->fetchByAssoc($result)) {
            $templateModule = $row['module'];
            $templateId = $row['templateid'];
            $templates[] = [
                'templateid'  => $templateId,
                'description' => $row['description'],
                'module'      => vtranslate($templateModule, $templateModule),
                'edit_url'    => 'index.php?module=PDFMaker&view=EditFree&return_view=List&templateid="' . $templateId,
            ];
        }

        return $templates;
    }

    //DetailView data
    public function GetDetailViewData($templateid)
    {
        $R_Atr = [$templateid, 'SalesOrder', 'Invoice', 'Quotes', 'PurchaseOrder'];
        $sql = 'SELECT vtiger_pdfmaker.*, vtiger_pdfmaker_settings.* FROM vtiger_pdfmaker LEFT JOIN vtiger_pdfmaker_settings USING(templateid) WHERE vtiger_pdfmaker.templateid=? AND vtiger_pdfmaker.module IN (?, ?, ?, ?)';

        $result = $this->db->pquery($sql, $R_Atr);
        $pdftemplateResult = $this->db->fetch_array($result);

        $pdftemplateResult['templateid'] = $templateid;

        return $pdftemplateResult;
    }

    //EditView data
    public function GetEditViewData($templateid)
    {
        $sql = 'SELECT vtiger_pdfmaker.*, vtiger_pdfmaker_settings.*
    			FROM vtiger_pdfmaker
    			LEFT JOIN vtiger_pdfmaker_settings USING(templateid)
    			WHERE vtiger_pdfmaker.templateid=?';

        $result = $this->db->pquery($sql, [$templateid]);
        $pdftemplateResult = $this->db->fetch_array($result);

        return $pdftemplateResult;
    }

    //function for getting the mPDF object that contains prepared HTML output
    //returns the name of output filename - the file can be generated by calling mPDF->Output(..) method
    public function GetPreparedMPDF(&$mpdf, $record, $module, $language)
    {
        $focus = CRMEntity::getInstance($module);

        foreach ($focus->column_fields as $cf_key => $cf_value) {
            $focus->column_fields[$cf_key] = '';
        }

        $focus->retrieve_entity_info($record, $module);
        $focus->id = $record;

        $PDFContent = $this->GetPDFContentRef($module, $focus, $language);
        $Settings = $PDFContent->getSettingsForModule($module);

        $pdf_content = $PDFContent->getContent();

        $header_html = $pdf_content['header'];
        $body_html = $pdf_content['body'];
        $footer_html = $pdf_content['footer'];

        // we need to set orientation for mPDF constructor in case of Custom format (array(width, length)) as well as we need to
        // set orientation for <pagebreak ... /> contruction
        if ($Settings['orientation'] == 'landscape') {
            $orientation = 'L';
        } else {
            $orientation = 'P';
        }

        $format = $Settings['format'];  // variable $format used in mPDF constructor
        $formatPB = $format;            // variable $formatPB used in <pagebreak ... /> contruction

        if (strpos($format, ';') > 0) {
            $tmpArr = explode(';', $format);
            $format = [$tmpArr[0], $tmpArr[1]];
            $formatPB = $format[0] . 'mm ' . $format[1] . 'mm';
        } elseif ($Settings['orientation'] == 'landscape') {
            $format .= '-L';
            $formatPB .= '-L';
        }

        $config = [
            'mode'              => '',
            'format'            => $format,
            'default_font_size' => 0,
            'default_font'      => '',
            'margin_left'       => $Settings['margin_left'],
            'margin_right'      => $Settings['margin_right'],
            'margin_top'        => 0,
            'margin_bottom'     => 0,
            'margin_header'     => $Settings['margin_top'],
            'margin_footer'     => $Settings['margin_bottom'],
            'orientation'       => $orientation,
        ];
        $mpdf = new PDFMaker_MPDF_Model($config);

        $this->mpdf_prepare_header_footer_settings($mpdf, $Settings);

        $mpdf->SetHTMLHeader($header_html);
        $mpdf->SetHTMLFooter($footer_html);
        $mpdf->WriteHTML($body_html);

        $name = $this->GenerateName($record, $module);

        $name = str_replace([' ', '/', ','], ['-', '-', '-'], $name);

        return $name;
    }

    public function GetPDFContentRef($module, $focus, $language)
    {
        return new PDFMaker_PDFContent_Model($module, $focus, $language);
    }

    private function mpdf_prepare_header_footer_settings(&$mpdf, &$Settings)
    {
        $disp_header = $Settings['disp_header'];
        $disp_optionsArr = ['dh_first', 'dh_other'];
        $disp_header_bin = str_pad(base_convert($disp_header, 10, 2), 2, '0', STR_PAD_LEFT);

        for ($i = 0; $i < count($disp_optionsArr); $i++) {
            if (substr($disp_header_bin, $i, 1) == '1') {
                $mpdf->PDFMakerDispHeader[$disp_optionsArr[$i]] = true;
            } else {
                $mpdf->PDFMakerDispHeader[$disp_optionsArr[$i]] = false;
            }
        }

        $disp_footer = $Settings['disp_footer'];
        $disp_optionsArr = ['df_first', 'df_last', 'df_other'];
        $disp_footer_bin = str_pad(base_convert($disp_footer, 10, 2), 3, '0', STR_PAD_LEFT);

        for ($i = 0; $i < count($disp_optionsArr); $i++) {
            if (substr($disp_footer_bin, $i, 1) == '1') {
                $mpdf->PDFMakerDispFooter[$disp_optionsArr[$i]] = true;
            } else {
                $mpdf->PDFMakerDispFooter[$disp_optionsArr[$i]] = false;
            }
        }
    }

    public function GenerateName($record, $module)
    {
        $templates = [];
        $focus = CRMEntity::getInstance($module);
        $focus->retrieve_entity_info($record, $module);

        $module_tabid = getTabId($module);
        $result = $this->db->pquery('SELECT fieldname FROM vtiger_field WHERE uitype=? AND tabid=?', ['4', $module_tabid]);
        $fieldname = $this->db->query_result($result, 0, 'fieldname');

        if (isset($focus->column_fields[$fieldname]) && $focus->column_fields[$fieldname] != '') {
            $name = $this->generate_cool_uri($focus->column_fields[$fieldname]);
        } else {
            $templatesStr = implode('_', $templates);
            $recordsStr = implode('_', $record);
            $name = $templatesStr . $recordsStr . date('ymdHi');
        }

        return $name;
    }

    function generate_cool_uri($name)
    {
        $Search = [
            '$',
            '€',
            '&',
            '%',
            ')',
            '(',
            '.',
            ' - ',
            '/',
            ' ',
            ',',
            'ľ',
            'š',
            'č',
            'ť',
            'ž',
            'ý',
            'á',
            'í',
            'é',
            'ó',
            'ö',
            'ů',
            'ú',
            'ü',
            'ä',
            'ň',
            'ď',
            'ô',
            'ŕ',
            'Ľ',
            'Š',
            'Č',
            'Ť',
            'Ž',
            'Ý',
            'Á',
            'Í',
            'É',
            'Ó',
            'Ú',
            'Ď',
            '"',
            '°',
            'ß'
        ];
        $Replace = [
            '',
            '',
            '',
            '',
            '',
            '',
            '-',
            '-',
            '-',
            '-',
            '-',
            'l',
            's',
            'c',
            't',
            'z',
            'y',
            'a',
            'i',
            'e',
            'o',
            'o',
            'u',
            'u',
            'u',
            'a',
            'n',
            'd',
            'o',
            'r',
            'l',
            's',
            'c',
            't',
            'z',
            'y',
            'a',
            'i',
            'e',
            'o',
            'u',
            'd',
            '',
            '',
            'ss'
        ];
        $return = str_replace($Search, $Replace, $name);

        // echo $return;
        return $return;
    }

    public function DeleteAllRefLinks()
    {
        require_once('vtlib/Vtiger/Link.php');
        $link_res = $this->db->pquery('SELECT tabid FROM vtiger_tab WHERE isentitytype=?', ['1']);

        while ($link_row = $this->db->fetchByAssoc($link_res)) {
            Vtiger_Link::deleteLink($link_row['tabid'], 'DETAILVIEWWIDGET', 'PDFMaker');
            Vtiger_Link::deleteLink($link_row['tabid'], 'LISTVIEWMASSACTION', 'PDF Export', 'javascript:getPDFListViewPopup2(this,\'$MODULE$\');');
        }
    }

    public function actualizeLinks()
    {
        $this->AddHeaderLinks();
    }

    public function AddHeaderLinks()
    {
        require_once('vtlib/Vtiger/Module.php');

        $link_module = Vtiger_Module::getInstance('PDFMaker');
        $link_module->addLink('HEADERSCRIPT', 'PDFMakerJS', 'layouts/v7/modules/PDFMaker/resources/PDFMakerActions.js', '', '1');
    }

    /**
     * Function to get the Quick Links for the module
     *
     * @param <Array> $linkParams
     *
     * @return <Array> List of Vtiger_Link_Model instances
     */
    public function getSideBarLinks($linkParams)
    {
        $currentUserModel = Users_Record_Model::getCurrentUserModel();

        $type = 'SIDEBARLINK';
        $quickLinks = [];

        if ($linkParams['ACTION'] == 'ProfilesPrivilegies') {
            $quickSLinks = [
                'linktype'  => 'SIDEBARLINK',
                'linklabel' => 'LBL_RECORDS_LIST',
                'linkurl'   => 'index.php?module=PDFMaker&view=List',
                'linkicon'  => ''
            ];

            $links['SIDEBARLINK'][] = Vtiger_Link_Model::getInstanceFromValues($quickSLinks);
        } elseif ($linkParams['ACTION'] == 'IndexAjax' && $linkParams['MODE'] == 'showSettingsList') {
            if ($currentUserModel->isAdminUser()) {
                $SettingsLinks = $this->GetAvailableSettings();

                foreach ($SettingsLinks as $stype => $sdata) {
                    $quickLinks[] = [
                        'linktype'  => 'SIDEBARLINK',
                        'linklabel' => $sdata['label'],
                        'linkurl'   => $sdata['location'],
                        'linkicon'  => ''
                    ];
                }
            }
        } else {
            $linkTypes = ['SIDEBARLINK', 'SIDEBARWIDGET'];
            $links = Vtiger_Link_Model::getAllByType($this->getId(), $linkTypes, $linkParams);

            $quickLinks[] = [
                'linktype'  => 'SIDEBARLINK',
                'linklabel' => 'LBL_RECORDS_LIST',
                'linkurl'   => $this->getListViewUrl(),
                'linkicon'  => '',
            ];
        }

        if (count($quickLinks) > 0) {
            foreach ($quickLinks as $quickLink) {
                $links[$type][] = Vtiger_Link_Model::getInstanceFromValues($quickLink);
            }
        }

        if ($currentUserModel->isAdminUser() && $linkParams['ACTION'] != 'Edit' && $linkParams['ACTION'] != 'Detail') {
            $quickS2Links = [
                'linktype'  => 'SIDEBARWIDGET',
                'linklabel' => 'LBL_SETTINGS',
                'linkurl'   => 'module=PDFMaker&view=IndexAjax&mode=showSettingsList&pview=' . $linkParams['ACTION'],
                'linkicon'  => ''
            ];
            $links['SIDEBARWIDGET'][] = Vtiger_Link_Model::getInstanceFromValues($quickS2Links);
        }

        return $links;
    }

    public function GetAvailableSettings()
    {
        $menu_array = [];

        return $menu_array;
    }

    public function getDetailViewLinks($templateid = '')
    {
        $linkTypes = ['DETAILVIEWTAB'];
        $detail_url = 'index.php?module=PDFMaker&view=DetailFree&templateid=' . $templateid . '&record=t' . $templateid;

        $detailViewLinks = [
            [
                'linktype'  => 'DETAILVIEWTAB',
                'linklabel' => vtranslate('LBL_PROPERTIES', 'PDFMaker'),
                'linkurl'   => $detail_url,
                'linkicon'  => ''
            ]
        ];

        foreach ($detailViewLinks as $detailViewLink) {
            $linkModelList['DETAILVIEWTAB'][] = Vtiger_Link_Model::getInstanceFromValues($detailViewLink);
        }

        return $linkModelList;
    }

    /**
     * @param $value
     * @return self
     */
    public static function getInstance($value = 'PDFMaker')
    {
        return new self();
    }

    /**
     * @param $actionKey
     * @return true
     */
    public function checkPermissions($actionKey)
    {
        return true;
    }

    /**
     * @return true
     */
    public function checkTemplatePermissions()
    {
        return true;
    }

    /**
     * @param string $module
     * @param bool $forListView
     * @param int|bool $recordId
     * @return array
     */
    public function getAvailableTemplates($module, $forListView = false, $recordId = false): array
    {
        $adb = PearDatabase::getInstance();
        $sql = 'SELECT templateid, filename, description FROM vtiger_pdfmaker WHERE module=? AND deleted=?';
        $result = $adb->pquery($sql, [$module, '0']);

        $templatesInfo = [];

        while ($row = $adb->fetchByAssoc($result)) {
            $templateId = intval($row['templateid']);
            $templatesInfo[$templateId] = [
                'template_id' => $templateId,
                'templatename' => $row['filename'],
                'title' => $row['description'],
                'is_default' => 3,
                'order' => 1,
                'disable_export_edit' => 1,
                'is_default_single_template' => 1,
            ];
        }

        return $templatesInfo;
    }

    /**
     * @param Vtiger_Request $request
     * @param string|array $templates
     * @param object $focus
     * @param array $records
     * @param string $fileName
     * @param string $moduleName
     * @param string $language
     * @return bool
     * @throws Exception
     */
    public function createPDFAndSaveFile($request, $templates, $focus, $records, $fileName, $moduleName, $language): bool
    {
        $documentId = $this->db->getUniqueID('vtiger_crmentity');

        if (is_array($templates)) {
            $templateIds = $templates;
        } else {
            $templates = trim($templates, ';');
            $templateIds = array_filter(explode(';', $templates));
        }

        if (empty($language)) {
            $language = Vtiger_Language_Handler::getLanguage();
        }

        $preContent = [];
        //called function GetPreparedMPDF returns the name of PDF and fill the variable $mpdf with prepared HTML output
        $mpdf = null;
        $name = $this->GetPreparedMPDF($mpdf, $records[0], $moduleName, $language);
        $name = $this->generate_cool_uri($name);

        $upload_file_path = decideFilePath();

        if (!empty($name)) {
            $fileName = $name . '.pdf';
        }

        $mpdf->Output($upload_file_path . $documentId . '_' . $fileName);

        $filesize = filesize($upload_file_path . $documentId . '_' . $fileName);
        $filetype = 'application/pdf';
        $description = $focus->column_fields['description'];
        $ownerId = $focus->column_fields['assigned_user_id'];

        $this->saveAttachment($documentId, $fileName, $description, $filetype, $upload_file_path, $ownerId);
        $this->saveAttachmentRelation($documentId, $focus->id);
        $this->db->pquery(
            'UPDATE vtiger_notes SET filesize=?, filename=? WHERE notesid=?',
            [$filesize, $fileName, $focus->id],
        );

        if (vtlib_isModuleActive('ModTracker')) {
            require_once 'modules/ModTracker/ModTracker.php';
            ModTracker::linkRelation($moduleName, $focus->parentid, 'Documents', $focus->id);
        }

        return true;
    }

    public function saveAttachmentRelation($documentId, $recordId): void
    {
        $this->db->pquery(
            'INSERT INTO vtiger_seattachmentsrel (crmid, attachmentsid) VALUES (?,?)',
            [$recordId, $documentId],
        );
    }

    /**
     * @param int $documentId
     * @param string $fileName
     * @param string $description
     * @param string $filetype
     * @param string $upload_file_path
     * @param int $ownerId
     * @return void
     */
    public function saveAttachment($documentId, $fileName, $description, $filetype, $upload_file_path, $ownerId): void
    {
        $createdTime = date('Y-m-d H:i:s');
        $currentUser = Users_Record_Model::getCurrentUserModel();

        if (empty($ownerId)) {
            $ownerId = $currentUser->id;
        }

        if (defined('STORAGE_ROOT')) {
            $upload_file_path = str_replace(STORAGE_ROOT, '', $upload_file_path);
        }

        $this->db->pquery(
            'INSERT INTO vtiger_crmentity (crmid,creator_user_id,assigned_user_id,setype,description,createdtime,modifiedtime) VALUES (?, ?, ?, ?, ?, ?, ?)',
            [
                $documentId,
                $currentUser->id,
                $ownerId,
                'Documents Attachment',
                $description,
                $this->db->formatDate($createdTime, true),
                $this->db->formatDate($createdTime, true),
            ]
        );

        $this->db->pquery(
            'INSERT INTO vtiger_attachments(attachmentsid, name, storedname, description, type, path) VALUES (?, ?, ?, ?, ?, ?)',
            [
                $documentId,
                $fileName,
                $fileName,
                $description,
                $filetype,
                $upload_file_path,
            ]
        );
    }
}